embed_dim: 256
latent_dim: 128
init_rotation_std: 0.01

vision_encoder:
  hidden_dims: [32, 64]

audio_encoder:
  hidden_dims: [32, 64, 128]

vision_decoder:
  hidden_dims: [64, 32]

audio_decoder:
  hidden_dims: [128, 64, 32]
